name: Hello World

on:
  workflow_dispatch:
    inputs:
      requested_for: 
        required: true
      ritm: 
        required: true
      reason:
        description: 'Reason for manual trigger'
        required: false

jobs:
  demo:
    runs-on: windows-latest

    steps:
    - name: runScpt
      run: | 
          Powershell -ExecutionPolicy Bypass -File /.github/Test/tstScript.ps1
      
